### ISSUE TITLE
Set torrent title in URL

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#102]
- https://github.com/torrust/torrust-index-frontend/blob/1b3137982eb6ae155d01e85e21ee733b8718611d/pages/torrent/%5BinfoHash%5D.vue#L79
- https://github.com/torrust/torrust-index-frontend/blob/1b3137982eb6ae155d01e85e21ee733b8718611d/pages/torrent/edit/%5BinfoHash%5D.vue#L147

**Comment by josecelano** [comment]
Our goals:

- We want to easily find a torrent bu its `infohash`.
- We want to easily find a torrent by its `title`.
- We want to include the torrent title in the torrent details page to improve SEO

### Proposal 1

For torrent list we have this URL:

- http://localhost:3000/torrents?search&sorting=UploadedDesc&pageSize=50&page=1&layout=default&categoryFilters=games

We can add two new parameters so you can find a torrent by infohash or title.

- http://localhost:3000/torrents?infohash=0c90fbf036e28370c1ec773401bc7620146b1d48
- http://localhost:3000/torrents?title=torrent-title

We could also use the `search` param as it uses the title. Maybe we only need to include the infohash in the SQL query condition if we detect an infohash in the search string.

For torrent details we replace the current URLs:

- http://localhost:3000/torrent/0c90fbf036e28370c1ec773401bc7620146b1d48

By:

- http://localhost:3000/torrent/torrent-title

For edition we can keep the infohash as it's not a public URL.

- http://localhost:3000/torrent/edit/0c90fbf036e28370c1ec773401bc7620146b1d48

In summary:

- We keep the current search but you can also use a infohash
- We change the torrent details page to use the title: http://localhost:3000/torrent/torrent-title

Pros:

- Simple changes
- Torrent details page is SEO friendly (at least the URl)

Cons:

- You need to click to reach a torrent by its infohash. First, you need to load: http://localhost:3000/torrents?search=0c90fbf036e28370c1ec773401bc7620146b1d48, and then you need to click on the results.

### Proposal 2

- We could change the torrent detail page: http://localhost:3000/torrent/0c90fbf036e28370c1ec773401bc7620146b1d48 to accept both an infohash or a title (http://localhost:3000/torrent/torrent-title). The component has to check whether the URL param is an infohash or not.

### Proposal 3

Include both the infohash and the title in the URL in the same URL segment:

http://localhost:3000/torrent/0c90fbf036e28370c1ec773401bc7620146b1d48-torrent-title

### Proposal 4

Include both the infohash and the title in the URL in different URL segments:

- http://localhost:3000/torrent/0c90fbf036e28370c1ec773401bc7620146b1d48/torrent-title
- http://localhost:3000/torrent/0c90fbf036e28370c1ec773401bc7620146b1d48

Pros:

- SEO could be improved (not sure what happens with duplicate content). We should try to make the one with the title the one crawled by search engines.
- User can use the direct form with only the infohash

### Proposal 5

Use duplicate URLs to access the same resource:

- http://localhost:3000/torrent/torrent-title
- http://localhost:3000/torrent/infohash/0c90fbf036e28370c1ec773401bc7620146b1d48

cc @da2ce7

**Comment by da2ce7** [comment]
Hello @josecelano 

Of your proposals I think that number 4 is the best.

The title for a torrent is non-unique and dynamically changing. While the Info-Hash of a torrent is static.

The title should be simply ignored, and used only for cosmetic/seo reasons. – I think that we should also limit it's length, and make sure we properly escape any special characters.

Cam.

**Comment by josecelano** [comment]
> Hello @josecelano
> 
> Of your proposals I think that number 4 is the best.
> 
> The title for a torrent is non-unique and dynamically changing. While the Info-Hash of a torrent is static.
> 
> The title should be simply ignored, and used only for cosmetic/seo reasons. – I think that we should also limit it's length, and make sure we properly escape any special characters.
> 
> Cam.

Hey @da2ce7 , cool! That's the one [I started to implement](https://github.com/torrust/torrust-index-frontend/pull/165).

By the way, I would change some URLs like the one for editing the torrent. This is the current one:

http://localhost:3000/torrent/edit/0c90fbf036e28370c1ec773401bc7620146b1d48

In general, I prefer:

- http://localhost:3000/torrent/0c90fbf036e28370c1ec773401bc7620146b1d48/edit
- http://localhost:3000/RESOURCE/RESOURCE-ID/SUB-RESOURCE-OR-ACTION

But with that approach, we wouldn't be able to put the title at the end.

And maybe there are some extra proposals:

### Proposal 6

- http://localhost:3000/torrent/0c90fbf036e28370c1ec773401bc7620146b1d48,url-encoded-title

I think this is the same as proposal 3. And it is not very common. Maybe it fits better for identifiers with multiple values (for example, location: latitude-longitude, point coordinates, etcetera)

### Extra considerations

Remember we were discussing that in the future the index could use other implementations to locate data: infohash V2, IPFS. Maybe it's not a good idea to use the infohash V1 as a unique ID in our URLs for our indexed content. Maybe we should use a sha-1 of an object like this:

```json
{
  "title": "title",
  "description": "description",
  "category": "category",
  "tags": [
    "tag1"
  ],
  "locator": {
    "protocol": "bittorrent",
    "version": "v1",
    "id": "0c90fbf036e28370c1ec773401bc7620146b1d48"
  }
}
```

It would be immutable, like the torrent file. If you change anything that represents a different classified data, even if the inner data it's the same. This implies we have to store the history and not only the latest state for the indexed content.

But I think this is out of the scope of this issue and our short-term goals.

### Links

- https://developers.google.com/search/docs/crawling-indexing/url-structure

### Notes

For now, the title is unique. We don't allow two torrents with the same title.

### Conclusion

I will continue implementing proposal 4, for now to release the version `3.0.0`.
