### ISSUE TITLE
Containerization documentation

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#183]
Parent: https://github.com/torrust/torrust-index-gui/issues/349
Relates to: https://github.com/torrust/torrust-index-frontend/issues/182

We have included support for docker in the [docker folder](https://github.com/torrust/torrust-index-frontend/tree/develop/docker/bin).

We have:

- A [Dockerfile](https://github.com/torrust/torrust-index-frontend/blob/develop/Dockerfile) for the webapp
- Docker [compose configuration](https://github.com/torrust/torrust-index-frontend/blob/develop/compose.yaml) for the E2E testing env.

There is no documentation for it except the [docker bin scripts](https://github.com/torrust/torrust-index-frontend/tree/develop/docker/bin) and [workflows](https://github.com/torrust/torrust-index-frontend/blob/develop/.github/workflows/test.yml#L27).

For now, docker is being used only to start an E2E testing env to run the E2E tests. But it could easily be re-used for production or development.

I'm planning to write an article for the [torrust blog](https://torrust.com/blog) in the future about how to deploy the Torrust solution (tracker +  index) to a virtual machine using docker-compose.

Documentation should be very similar to the one we wrote for the Tracker and Backend:

- [Torrust Tracker docker support documentation](https://github.com/torrust/torrust-tracker/tree/develop/docker)
- [Torrust Index Backend docker support documentation](https://github.com/torrust/torrust-index-backend/tree/develop/docker)

cc @da2ce7

**Comment by da2ce7** [comment]
The docker documentations is good to keep maintained inside of the repository.

**Comment by josecelano** [comment]
There have been a lot of changes since I opened this issue. See https://github.com/torrust/torrust-index-gui/issues/349. Documentation should take into consideration those changes.

We also have to explain in the documentation how you can overwrite the ABI BASE URL at runtime if you are using node. See https://github.com/torrust/torrust-index-gui/issues/182. I'm going to close that issue. We will include that info in this issue.
