### ISSUE TITLE
Upgrade to the next major version of eslint-plugin

### ISSUE THREAD

**Issue by da2ce7** [torrust/torrust-index-gui#192]
Automated dependabot upgraded the package but the workflows fail: https://github.com/torrust/torrust-index-frontend/pull/174

**Comment by Wolfremium13** [comment]
Hello maybe we need to update to the same version the dependency `"@typescript-eslint/parser": "^6.1.0"` tried on my local machine and it works. Link to the [PR](https://github.com/torrust/torrust-index-frontend/pull/194)
