### ISSUE TITLE
Admins should have User Management Capabilities

### ISSUE THREAD

**Issue by da2ce7** [torrust/torrust-index-gui#284]
Administrators should have the to preform the following actions to users:

- Activate
- Disable / Enable
- Reset Password
- Delete
- Ban / Unban

**Comment by da2ce7** [comment]
@josecelano noted that the [index backend already supports banning users](https://docs.rs/torrust-index-backend/latest/torrust_index_backend/web/api/v1/contexts/user/index.html#ban-a-user).

**Comment by da2ce7** [comment]
@WarmBeer suggested that we can have some option to enable an activation queue for new users; so that administrators can check user accounts before activating them.

**Comment by josecelano** [comment]
> @josecelano noted that the [index backend already supports banning users](https://docs.rs/torrust-index-backend/latest/torrust_index_backend/web/api/v1/contexts/user/index.html#ban-a-user).

Yes, I think that was something (maybe) we lost when we migrated to Nuxt.

**Comment by josecelano** [comment]
I'm organising user management issues on [this epic](https://github.com/torrust/torrust-index-gui/issues/657).
