### ISSUE TITLE
`postcss.config.js` is not supported together with Nuxt

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#352]
WHen you run `npm run dev` you get this warning:

```
 WARN  Using postcss.config.js is not supported together with Nuxt. Use options.postcss instead. You can read more in https://nuxt.com/docs/api/configuration/nuxt-config#postcss. 
```

It seems we are not using that file: https://github.com/torrust/torrust-index-gui/blob/develop/postcss.config.js

```
module.exports = {
  plugins: {
    "tailwindcss/nesting": {},
    tailwindcss: {},
    autoprefixer: {}
  }
};
```

We should delete it and move its contents to nuxt.config.ts (if I'm not wrong).

**Comment by cgbosse** [comment]
@josecelano is this an easy issue could this be done by one of the juniors?

**Comment by josecelano** [comment]
> @josecelano is this an easy issue could this be done by one of the juniors?

Hi @cgbosse yes, I guess so.
