### ISSUE TITLE
Not Found page retusn a 200 status code

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#406]
![image](https://github.com/torrust/torrust-index-gui/assets/58816/98300e68-c660-49d2-b113-085fc21f66c4)

If you try to load a non-existing page you see the "Not Found" page but it returns a 200 HTTP status.

Shouldn't a 404 be returned?

**Comment by cgbosse** [comment]
@mario-nt 
for you ;)

**Comment by josecelano** [comment]
It seems to be the standard behaviour when you are rendering only on the browser.

In Nuxt.js, the `ssr` (Server-Side Rendering) configuration option controls whether your application should render pages on the server (server-side) or entirely in the browser (client-side). When you set `ssr: false` in your Nuxt configuration (`nuxt.config.js`), you're opting for a fully client-side rendered application.

Here's a brief explanation of what this means:

1. **Server-Side Rendering (SSR) `ssr: true`**: 
   - By default, Nuxt.js pre-renders all pages on the server. This means that the HTML is fully rendered on the server and sent to the client. 
   - Benefits include improved SEO and faster initial page load times since the content is immediately available for display and indexing by search engines.
   - Each page request is processed by the server, so it can return the appropriate HTTP status code, like 404 for not found pages.

2. **Client-Side Rendering (CSR) `ssr: false`**:
   - When you set `ssr: false`, Nuxt.js doesn't pre-render pages on the server. Instead, it serves a generic, unpopulated HTML shell that gets populated in the client's browser.
   - Since the server sends the same generic HTML file for every request, it typically returns a 200 OK status for every page, even if the page doesn't exist in your application. The handling of non-existent pages (404) is then managed client-side by the JavaScript loaded in the browser.
   - This mode is useful for applications where SEO is not a concern, or for specific parts of an application (like admin panels), but it loses the SEO and performance benefits of server-side rendering.

### Handling 404 Pages in CSR Mode

When running in CSR mode (`ssr: false`), you need to handle 404 pages client-side. Nuxt.js provides a way to customize the 404 page:

- Create a `layouts/error.vue` file to define a custom error layout.
- In this layout, you can check for a 404 error and display an appropriate message or design.

However, remember that in CSR mode, the server always returns a 200 status for all paths, and the 404 handling is purely cosmetic from the user's perspective.

### Conclusion

Setting `ssr: false` is a decision that impacts SEO, performance, and how your application handles routing and errors. It's essential to consider these factors based on the needs of your application and its users. For applications where SEO is crucial, it's generally recommended to use SSR or static site generation (with `target: 'static'`).
