### ISSUE TITLE
Token invalid | 401 Unauthorized error when loading the page

### ISSUE THREAD

**Issue by mario-nt** [torrust/torrust-index-gui#424]
A 401 Unauthorized error is shown when opening the index GUI with Firefox:
![image](https://github.com/torrust/torrust-index-gui/assets/141633147/a7e5c992-e12d-4975-ba6e-1b8173feb761)
**Detail:**
![image](https://github.com/torrust/torrust-index-gui/assets/141633147/57a998af-7479-4949-ba54-002e50891e4a)

**Comment by cgbosse** [comment]
@mario-nt any progress on this?
What is your priority with this issue?

**Comment by mario-nt** [comment]
@cgbosse I haven't started working on it yet, I'm planning of finishing the light/dark mode PR and then continue with the rest of the issues/PRs I have assigned. I would start prioritizing the issues that will be part of the V3.0 release and critical bugs and errors from now on.

**Comment by josecelano** [comment]
This is a problem described [here](https://github.com/torrust/torrust-index/issues/39#issuecomment-1910668709). 

My first thought was we should discard the token in this case (if the user was removed). But we do not know if the user was removed or does not have permission to see that resource anymore.

Maybe we have to keep the frontend as it is. The users should receive a notification that their accounts were removed. So they must know why they do not have access anymore to a resource.

Alternatively, we could check that the account still exists. but I do not think that's a good idea. Accounts should not be removed like that.

I'm going to close the issue. Feel free to open it again if you think I'm wrong or there is a better approach to this.

cc @WarmBeer @da2ce7
