### ISSUE TITLE
Inconsistent font style in torrent details page

### ISSUE THREAD

**Issue by mario-nt** [torrust/torrust-index-gui#448]
Some of the torrent fields in the torrent detail page has an inconsistent style:

![image](https://github.com/torrust/torrust-index-gui/assets/141633147/0ef77b09-60ad-41c2-a349-da2991959fd9)

Creation date for example, has a brighter color, almost with a bold style, while others, like created by, has a darker font color.

**Comment by mario-nt** [comment]
Hi @ngthhu, I am reopening the issue because when there is no data, for example, when no comment is provided, the font color is still slightly brighter.

Feel free to fix it yourself if you want or someone in the team will do it.

**Comment by hungfnt** [comment]
Hi @mario-nt, I thought the 'No description' text was designed to be different, I'll fix it.

**Comment by mario-nt** [comment]
> Hi @mario-nt, I thought the 'No description' text was designed to be different, I'll fix it.

Hi, yup, I would keep the italic, but use the same font color as the fields with info, if you have any suggestions feel free to speak up.
