### ISSUE TITLE
Make the torrent title more visible on the torrent details page

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#456]
I'm not a designer but I would suggest moving the torrent title to the left. What so you think @mario-nt?

![image](https://github.com/torrust/torrust-index-gui/assets/58816/4ad34fcd-fd8e-4fa7-bf25-4cb6f2ba56c8)

Screenshot link: https://index.torrust-demo.com/torrent/54cfe9ef983caf4ee8acf7ad66257dd461036f35

**Comment by mario-nt** [comment]
> I'm not a designer but I would suggest moving the torrent title to the left. What so you think @mario-nt?
> 
> ![image](https://private-user-images.githubusercontent.com/58816/299764726-4ad34fcd-fd8e-4fa7-bf25-4cb6f2ba56c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTg5MDksIm5iZiI6MTcwNjY5ODYwOSwicGF0aCI6Ii81ODgxNi8yOTk3NjQ3MjYtNGFkMzRmY2QtZmQ4ZS00ZmE3LWJmMjUtNGNiNmYyYmE1NmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwNTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMjhiYmQ3ODAwN2EwMGI3MDg4YTJkZGM4OGY5ZDg1NWYyMzI0YjMwOTkwMjEzYmJjMjU1MjJkMWJmYTMwYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p0zeOZ1BZ8rsfT3OKnihhdnGYJ7UnqgQXtbLotwS-nw)
> 
> Screenshot link: https://index.torrust-demo.com/torrent/54cfe9ef983caf4ee8acf7ad66257dd461036f35

I think it is a really good idea, I'll take at look at it and see how we can change it!
