### ISSUE TITLE
Allow users to change their passwords

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#468]
Depends on: https://github.com/torrust/torrust-index/issues/618

Relates to: 
- https://github.com/torrust/torrust-index-gui/issues/469
- https://github.com/torrust/torrust-index/issues/507

Currently, there is no option to change your password after signing up. This is a very basic and critical feature. If the password is compromised you can't change it.

I would suggest adding a profile setting page with only this option for the time being.

cc @torrust/torrustaceans

**Comment by cgbosse** [comment]
Makes sense.

**Comment by josecelano** [comment]
This should not have been closed. I've implemented only this https://github.com/torrust/torrust-index-gui/issues/469

**Comment by josecelano** [comment]
> This should not have been closed. I've implemented only this #469

In the end, I was confused. It was this issue that one implemented in https://github.com/torrust/torrust-index-gui/issues/468
