### ISSUE TITLE
Long line in the torrents description are rendered outside of the description div

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#525]
![image](https://github.com/torrust/torrust-index-gui/assets/58816/fc293e65-b9f2-4c76-a82d-48a591de6e0c)

**Comment by hungfnt** [comment]
Hey, I noticed the descriptions for each torrent in the list weren't word-wrapped. I'm adding it now.
We can use the class `break-words` in `Markdown` instead of all Tab components.

**Comment by hungfnt** [comment]
The markdown width should be inherit from parent div.

![image](https://github.com/torrust/torrust-index-gui/assets/167511750/fd91c105-08ce-4559-97af-c1619aec4a71)

When I use `class="prose max-w-none text-justify break-words"` for div of Markdown, everything is good except the overflow word.

<p float="left">
  <img src="https://github.com/torrust/torrust-index-gui/assets/167511750/660ab7a8-08bd-47a4-9eb2-9609088a6c39"  width="500"/>
  <img src="https://github.com/torrust/torrust-index-gui/assets/167511750/381d256f-9c22-4fa6-9f66-b20e4631eb83" width="500"/>
</p>

With `break-all`, the long-word case is handled well, but normal paragraphs lose readability.

<p float="left">
  <img src="https://github.com/torrust/torrust-index-gui/assets/167511750/e03fc240-07ac-4ef3-981c-c070fade57a3"  width="500"/>
  <img src="https://github.com/torrust/torrust-index-gui/assets/167511750/4cb439e8-4b59-43f5-96a3-4e9844059d3c" width="500"/>
</p>

Followed this [solution](https://stackoverflow.com/a/18706058), 2 cases are good.

<p float="left">
  <img src="https://github.com/torrust/torrust-index-gui/assets/167511750/994bc4be-d855-4936-b78c-ddc1f616fdcb" width="500"/>
  <img src="https://github.com/torrust/torrust-index-gui/assets/167511750/a42866f0-075e-47d4-81f7-fbf2be7c436c"  width="500"/>
</p>
