### ISSUE TITLE
Manually upload file not working

### ISSUE THREAD

**Issue by grmbyrn** [torrust/torrust-index-gui#532]
When uploading a torrent, only the option to drag and drop a file works. The `Manually upload a file` link doesn't work.

<img width="888" alt="Screenshot 2024-04-22 at 13 38 35" src="https://github.com/torrust/torrust-index-gui/assets/95353365/72b27710-f66f-414f-a7fe-1f343c231d56">

Also, when the user has chosen a torrent to upload, the link which should allow them to `Upload a different file` doesn't work.

<img width="888" alt="Screenshot 2024-04-22 at 13 42 51" src="https://github.com/torrust/torrust-index-gui/assets/95353365/10608cef-5fa4-4a20-a391-88cb6ab3b6af">

**Comment by hungfnt** [comment]
The `Manually upload a file` and `Upload a different file` links work fine for me, I suggest that we can click anywhere inside the box instead of just the text.

**Comment by josecelano** [comment]
Hi @grmbyrn, It works if you click on the text. In my case, what does not work is changing the mouse pointer on hover. I would implement what @ngthhu suggested: allow clicking on the whole box.

What browser are you using? I've tested it with:

- Chrome: Version 124.0.6367.60 (Official Build) (64-bit)
- Brave: 1.65.114 (Apr 17, 2024)
- Firefox: 125.0.1

**Comment by grmbyrn** [comment]
> Hi @grmbyrn, It works if you click on the text. In my case, what does not work is changing the mouse pointer on hover. I would implement what @ngthhu suggested: allow clicking on the whole box.
> 
> What browser are you using? I've tested it with:
> 
> * Chrome: Version 124.0.6367.60 (Official Build) (64-bit)
> * Brave: 1.65.114 (Apr 17, 2024)
> * Firefox: 125.0.1

Hi @josecelano, I was using Version 122.0.6261.69 (Official Build) (arm64), but I just updated it to Version 124.0.6367.62 (Official Build) (arm64) and it works fine now. I also tried it on Safari Version 17.1 (17616.2.9.11.9, 17616) and that works fine as well.

I like @ngthhu idea of being able to click anywhere inside the box instead of just the text.
