### ISSUE TITLE
Suggestion: pass torrent.description from TorrentList to TorrentListTorrentDetails

### ISSUE THREAD

**Issue by hungfnt** [torrust/torrust-index-gui#533]
The `TorrentListTorrentDetails` component only displays the `torrent.description`. Therefore, I think it's redundant to pass the `torrent.info_hash` and call the API each time a list item is clicked.

**Comment by josecelano** [comment]
Hi @ngthhu good catch! That would be a good improvement. We can just pass the description from the parent component `TorrentList` and remove the extra API call.

Maybe, in the beginning, the intention was to show more info.

**Comment by hungfnt** [comment]
There is one more thing: when the description includes links to images, it takes some time to load. Should we consider pre-rendering?

**Comment by josecelano** [comment]
> There is one more thing: when the description includes links to images, it takes some time to load. Should we consider pre-rendering?

Hi @ngthhu The reason is we are using a [proxy for the images](https://github.com/torrust/torrust-index-gui/issues/522). There is an [open issue to use a skeleton while the app is fetching the data](https://github.com/torrust/torrust-index-gui/issues/411).
