### ISSUE TITLE
Add a new link to User Guide

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#547]
I've moved the documentation for end users to this repo:

https://github.com/torrust/torrust-index-gui-user-guide

It's deployed to GitHub pages here:

https://torrust.github.io/torrust-index-gui-user-guide/

For the time being, it is elementary, but we are planning to add more sections.

It would be helpful to add a new "Help" link to this menu:

![image](https://github.com/torrust/torrust-index-gui/assets/58816/d0fe93ed-a580-4942-aea2-490a5994d496)

So users can easily find the documentation.

**Comment by anujkumardarji** [comment]
I have created pull request #548  to address this issue. Please review and let me know if any further changes are needed.
