### ISSUE TITLE
JSON.parse bug

### ISSUE THREAD

**Issue by ghost** [torrust/torrust-index-gui#600]
Hey,
Steps to reproduce:
1. Go to https://index.torrust-demo.com/torrents.
2. Select a tag to isolate torrents (e.g. `librivox`).
3. Go back a page.
4. Behavior occurs
a. page goes blank
b. sorting fields disappear
c. error message appears: `Trying to get the information for the torrents. JSON.parse:unexpected character at line 1 column 1 of the JSON data.`

Preview:
![bugs (3)](https://github.com/user-attachments/assets/8344d8db-7490-4f32-9064-00e0ed428ef4)

Thanks,

**Comment by josecelano** [comment]
The synchronization between the URL parameters and the internal component state is messy. I'm not sure if we should remove the internal state and just use the parameters to make it simpler. Anyway, I think I have patched it [here](https://github.com/torrust/torrust-index-gui/pull/604).

**Comment by josecelano** [comment]
Updated also on the [live demo](https://index.torrust-demo.com/torrents).

**Comment by ghost** [comment]
Appreciate the fix, thanks.
