### ISSUE TITLE
t.tags.join bug

### ISSUE THREAD

**Issue by ghost** [torrust/torrust-index-gui#601]
Hey,
Steps to reproduce:
1. Go to https://index.torrust-demo.com/torrents.
2. Select a tag, remove it.
3. Select another tag, remove it.
4. Go back a page.
5. Behavior occurs:
a. category dropdown disapears
b. tags box marks 'Multiple', with the last chosen tag still checked in the dropdown
c. error message pops up stating `Trying to get the information for the torrents. t.tags.join is not a function.`

Preview: 
![bugs (2)](https://github.com/user-attachments/assets/e575a923-14ab-4102-97ff-b1c7da449a1c)

Thanks,

**Comment by josecelano** [comment]
Also updated on the [demo site](https://index.torrust-demo.com/torrents). Thank you for reporting it.

**Comment by ghost** [comment]
Appreciate the fix, thanks.
