### ISSUE TITLE
New static page: Usage Policies and Content Restrictions

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#617]
Parent issue: https://github.com/torrust/torrust-index-gui/issues/614

**Title:** Usage Policies and Content Restrictions

**Content:**  
"Our software is designed to support the distribution of legal, authorized content only. Users may only upload or share files that fall under the following categories:

- **Open-Source Licenses:** Content licensed under recognized open-source licenses, allowing for free distribution and modification.
- **Creative Commons Licenses:** Content released under Creative Commons licenses that permit sharing and distribution.
- **Public Domain:** Content that is free of copyright restrictions and available for public use.

**Prohibited Content:** Any content that infringes copyright, is subject to copyright protection, or is illegal under applicable laws is strictly prohibited. This includes but is not limited to copyrighted movies, music, software, books, and any other media.

**Enforcement:** We reserve the right to remove any content that does not comply with these policies without notice. We may also take additional steps, including reporting violations to the relevant authorities, if necessary."

**Comment by da2ce7** [comment]
Looks good for me.
