### ISSUE TITLE
Use DaisyUI's notification component

### ISSUE THREAD

**Issue by mickvandijke** [torrust/torrust-index-gui#72]

**Comment by josecelano** [comment]
Hey @WarmBeer do you mean the alert component (https://daisyui.com/components/alert/)? And when would you put it? Now it's at the bottom of the page. Why do you want to change it? Because you want to migrate al components to DaisyUI components?

**Comment by mickvandijke** [comment]
Hi @josecelano ,

My plan was to migrate most components to DaisyUI to make color theming easier. But for the notification component I think it is no longer necessary. The notification component looks good as is in my opinion.
