### ISSUE TITLE
Make the `develop` branch the default branch again

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#78]
Hi @WarmBeer I suppose the `nuxt-3` branch is finished as it's the default one. I think we cold merge into `develop` and make `develop` the default branch again.

cc @da2ce7

**Comment by da2ce7** [comment]
Hello Jose,Yes, let’s reset  the ‚develop’ branch to the head of the ‚nuxt-3‘ branch. Then make it the default.I changed to the ‚nuxt-3’ branch as the default as I found the ‚develop‘ branch to be too-stale and misleading people who may visit.Cam.On 20.06.2023, at 18:27, Jose Celano ***@***.***> wrote:﻿
Hi @WarmBeer I suppose the nuxt-3 branch is finished as it's the default one. I think we cold merge into develop and make develop the default branch again.
cc @da2ce7

**Comment by josecelano** [comment]
Done.
