### ISSUE TITLE
Clean browser console warnings

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#96]
There are some warnings on the browser console when you run the app. Some of them are:

![image](https://github.com/torrust/torrust-index-frontend/assets/58816/76ea3175-4675-46cc-b066-55a78d1ea766)

It would be nice to clean them to make it easier to identify actual errors.

- [ ] Incorrect use of `label for=FORM_ELEMENT`
- [ ] ...

**Comment by josecelano** [comment]
I've cleaned some in [this commit](9c5740a2c84de9867f8c1ca99e30990619c8ac94). There are still some of them:

![image](https://github.com/torrust/torrust-index-frontend/assets/58816/2ddebe31-65f5-41e0-be90-b3bb9b82e250)

**Comment by josecelano** [comment]
Errors in this issue description have been fixed but we have to fix also the ones in the "issues" tab.

**Comment by Wolfremium13** [comment]
I created a [PR](https://github.com/torrust/torrust-index-frontend/pull/191) for this issue 😼.

**Comment by josecelano** [comment]
It seems this is the only error we have now:

![image](https://github.com/torrust/torrust-index-frontend/assets/58816/9721fa12-48a1-4583-a2a6-8572fa3a092d)

And it's from a dependency. Thank @Wolfremium13 !
